[package]
name = "vex_sys"
description = "A library for autonomously controlling VEX robots."
repository = "https://github.com/tropix126/vexnav/"
authors = ["Tropical"]
license-file = "LICENSE.md"
categories = ["science::robotics", "no-std", "mathematics", "embedded"]
keywords = ["vex", "pros", "pros-rs", "vex-robotics", "robotics", "autonomous"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pros = { git = "https://github.com/pros-rs/pros-rs" }
num-traits = { version = "0.2", default-features = false, features = ["libm"] }