[package]
name = "vex-sdk"
description = "Raw bindings to vexos user jump table functions."
repository = "https://github.com/pros-rs/vex-sys/"
authors = ["Tropical"]
license-file = "LICENSE.md"
categories = ["science::robotics", "no-std", "embedded"]
keywords = ["vex", "vex-v5", "vex-robotics", "robotics"]
version = "0.16.1"
edition = "2021"
crate-type = ["staticlib"]

[dependencies]
rustc-std-workspace-core = { version = "1.0.0", optional = true }

[features]
rustc-dep-of-std = ["rustc-std-workspace-core"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html