[package]
name = "vex-sdk-jumptable"
description = "VEX SDK implementation using VEXos jump table addresses."
repository = "https://github.com/vexide/vex-sdk/"
authors = ["Tropical"]
license = "MIT"
categories = ["science::robotics", "no-std", "embedded"]
keywords = ["vex", "vex-v5", "vex-robotics", "robotics"]
version = "0.0.1"
edition = "2021"
links = "vex-sdk"

[dependencies]
vex-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["armv7a-vex-v5"]
cargo-args=[
    "-Zbuild-std=core,alloc,compiler_builtins",
    "-Zbuild-std-features=compiler-builtins-mem"
]
