[package]
name = "vex-sdk-vexcode"
description = "A build script helper to download and link to official VEXcode SDKs."
repository = "https://github.com/vexide/vex-sdk/"
authors = ["Tropical"]
license = "MIT"
categories = ["science::robotics", "embedded"]
keywords = ["vex", "vex-v5", "vex-robotics", "robotics"]
version = "0.0.1"

[dependencies]
zip = "4.5.0"
serde = { version = "1.0", features = ["derive"] }
ureq = { version = "3.1.0", features = ["json"] }
